name: mathquest
description: "MathQuest — Application mobile d'apprentissage gamifié des mathématiques"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # State Management
  provider: ^6.1.2

  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.1

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  shimmer: ^3.0.0

  # Navigation
  go_router: ^14.2.0

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: 10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
